language: swift
osx_image: xcode10.2
cache:
- bundler
git:
  depth: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- bundle install
- echo -e "machine github.com\n  login $CI_GITHUB_TOKEN" >> ~/.netrc
script:
- set -o pipefail
- fastlane store

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  on:
    all_branches: true
    condition: "`cat status` = SUCCESS"
  provider: releases
  api_key: "$CI_GITHUB_TOKEN"
  file_glob: true
  file: fastlane/artifacts/*
  skip_cleanup: true
