language: swift
osx_image: xcode10.2
cache:
- bundler
git:
  depth: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- bundle install
- echo -e "machine github.com\n  login $CI_GITHUB_TOKEN" >> ~/.netrc
script:
- set -o pipefail
- fastlane create_release
