default_platform(:ios)

$appStoreProvisioningFile = "#{ENV["MATCH_OUTPUT_PATH"]}/AppStore_com.archano.ios.Fastlane-Playground.mobileprovision"
$ipaFile = "#{ENV["GYM_OUTPUT_DIRECTORY"]}/Fastlane Playground.ipa"
$dSYMFile = "#{ENV["GYM_OUTPUT_DIRECTORY"]}/Fastlane Playground.app.dSYM.zip"

platform :ios do

	desc "Clean"
	lane :clean do
		xcclean
	end

	desc "Build for AppStore"
	lane :store do
		setup_travis
		sync_code_signing(type: "appstore")
		update_project_team
		update_project_provisioning(profile: $appStoreProvisioningFile)
		build_ios_app(
			clean: true,
			codesigning_identity: "iPhone Distribution",
			silent: true,
			include_symbols: true,
			include_bitcode: false,
			skip_profile_detection: true,
			export_options: {
			    uploadBitcode: false,
			    uploadSymbols: true,
			    compileBitcode: false
			}
		)
	end

	desc "Upload to AppStore"
	lane :upload_release_candidate do
		upload_to_app_store(
			ipa: $ipaFile,
			phased_release: true,
			submit_for_review: false,
			skip_screenshots: true,
			skip_metadata: true
		)
	end

	lane :create_release do
		set_github_release(
		  repository_name: ENV["TRAVIS_REPO_SLUG"],
		  api_token: ENV["CI_GITHUB_TOKEN"],
		  name: "Release 0.0.0",
		  tag_name: "v0.0.0",
		  description: "Some description",
		  commitish: ENV["TRAVIS_BRANCH"],
		  upload_assets: [$ipaFile, $dSYMFile]
		)
	end

end
