default_platform(:ios)

appStoreProvisioningFile = "#{ENV["MATCH_OUTPUT_PATH"]}/AppStore_com.archano.ios.Fastlane-Playground.mobileprovision"

platform :ios do

	desc "Build for AppStore"
	lane :store do
		sync_code_signing(type: "appstore")
		update_project_team
		update_project_provisioning(profile: appStoreProvisioningFile)
		build_ios_app(
			clean: true,
			codesigning_identity: "iPhone Distribution"
		)
	end

end
